ADVISORY_SIMULATION_CONTRACT_VERSION = "advisory-simulation.v1"
ADVISORY_SIMULATION_CONTRACT_VERSION_HEADER = "X-Lotus-Contract-Version"

__all__ = [
    "ADVISORY_SIMULATION_CONTRACT_VERSION",
    "ADVISORY_SIMULATION_CONTRACT_VERSION_HEADER",
]
