from __future__ import annotations

from src.core.advisory_copilot.api_validation import (
    COPILOT_ACTOR_ID_MAX_LENGTH,
    COPILOT_IDENTIFIER_MAX_LENGTH,
    COPILOT_USER_INSTRUCTION_MAX_LENGTH,
)

COPILOT_CURSOR_MAX_LENGTH = 512
COPILOT_REQUESTED_OUTPUT_LIMIT = 8
COPILOT_REQUESTED_OUTPUT_MAX_LENGTH = 96
COPILOT_REQUESTED_INTENT_LIMIT = 12
COPILOT_REQUESTED_INTENT_MAX_LENGTH = 96
COPILOT_SUPPORTABILITY_BOUNDARY_LIMIT = 12
COPILOT_SUPPORTABILITY_BOUNDARY_MAX_LENGTH = 160
COPILOT_SUPPORTABILITY_STATUS_MAX_LENGTH = 160

__all__ = [
    "COPILOT_ACTOR_ID_MAX_LENGTH",
    "COPILOT_CURSOR_MAX_LENGTH",
    "COPILOT_IDENTIFIER_MAX_LENGTH",
    "COPILOT_REQUESTED_INTENT_LIMIT",
    "COPILOT_REQUESTED_INTENT_MAX_LENGTH",
    "COPILOT_REQUESTED_OUTPUT_LIMIT",
    "COPILOT_REQUESTED_OUTPUT_MAX_LENGTH",
    "COPILOT_SUPPORTABILITY_BOUNDARY_LIMIT",
    "COPILOT_SUPPORTABILITY_BOUNDARY_MAX_LENGTH",
    "COPILOT_SUPPORTABILITY_STATUS_MAX_LENGTH",
    "COPILOT_USER_INSTRUCTION_MAX_LENGTH",
]
