from __future__ import annotations

COPILOT_IDEMPOTENCY_RECORD_HASH_MAX_LENGTH = 128
COPILOT_IDEMPOTENCY_RECORD_IDENTIFIER_MAX_LENGTH = 160

__all__ = [
    "COPILOT_IDEMPOTENCY_RECORD_HASH_MAX_LENGTH",
    "COPILOT_IDEMPOTENCY_RECORD_IDENTIFIER_MAX_LENGTH",
]
