from __future__ import annotations

COPILOT_PACKET_RECORD_ACTOR_ID_MAX_LENGTH = 128
COPILOT_PACKET_RECORD_HASH_MAX_LENGTH = 128
COPILOT_PACKET_RECORD_IDENTIFIER_MAX_LENGTH = 160
COPILOT_PACKET_RECORD_JSON_FIELD_MAX_ITEMS = 64

__all__ = [
    "COPILOT_PACKET_RECORD_ACTOR_ID_MAX_LENGTH",
    "COPILOT_PACKET_RECORD_HASH_MAX_LENGTH",
    "COPILOT_PACKET_RECORD_IDENTIFIER_MAX_LENGTH",
    "COPILOT_PACKET_RECORD_JSON_FIELD_MAX_ITEMS",
]
