from __future__ import annotations

COPILOT_RUN_ACTOR_ID_MAX_LENGTH = 128
COPILOT_RUN_APP_ID_MAX_LENGTH = 64
COPILOT_RUN_HASH_MAX_LENGTH = 128
COPILOT_RUN_IDENTIFIER_MAX_LENGTH = 160
COPILOT_RUN_JSON_FIELD_MAX_ITEMS = 64
COPILOT_RUN_OUTPUT_SECTION_LIMIT = 64
COPILOT_RUN_REVIEW_GUIDANCE_LIMIT = 16
COPILOT_RUN_REVIEW_GUIDANCE_MAX_LENGTH = 500
COPILOT_RUN_GUARDRAIL_REASON_LIMIT = 16
COPILOT_RUN_GUARDRAIL_REASON_MAX_LENGTH = 160
COPILOT_RUN_VERSION_REF_MAX_LENGTH = 160

__all__ = [
    "COPILOT_RUN_ACTOR_ID_MAX_LENGTH",
    "COPILOT_RUN_APP_ID_MAX_LENGTH",
    "COPILOT_RUN_GUARDRAIL_REASON_LIMIT",
    "COPILOT_RUN_GUARDRAIL_REASON_MAX_LENGTH",
    "COPILOT_RUN_HASH_MAX_LENGTH",
    "COPILOT_RUN_IDENTIFIER_MAX_LENGTH",
    "COPILOT_RUN_JSON_FIELD_MAX_ITEMS",
    "COPILOT_RUN_OUTPUT_SECTION_LIMIT",
    "COPILOT_RUN_REVIEW_GUIDANCE_LIMIT",
    "COPILOT_RUN_REVIEW_GUIDANCE_MAX_LENGTH",
    "COPILOT_RUN_VERSION_REF_MAX_LENGTH",
]
