from __future__ import annotations

from typing import Literal

AdvisorCockpitActionStatus = Literal[
    "READY",
    "PENDING_REVIEW",
    "BLOCKED",
    "ACKNOWLEDGED",
    "HANDOFF_REQUESTED",
    "COMPLETED",
    "SUPERSEDED",
]
AdvisorCockpitActionPriority = Literal["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"]
AdvisorCockpitOwnerRole = Literal[
    "ADVISOR",
    "DESK_HEAD",
    "COMPLIANCE_REVIEWER",
    "INVESTMENT_DESK",
    "PORTFOLIO_MANAGER",
    "OPERATIONS",
    "CRM_OWNER",
    "REPORTING_OWNER",
    "ARCHIVE_OWNER",
    "EXECUTION_OWNER",
    "SYSTEM",
]
AdvisorCockpitCallerRole = Literal[
    "ADVISOR",
    "DESK_HEAD",
    "COMPLIANCE_REVIEWER",
    "INVESTMENT_DESK",
    "PORTFOLIO_MANAGER",
    "OPERATIONS",
    "CRM_OWNER",
    "REPORTING_OWNER",
    "ARCHIVE_OWNER",
    "EXECUTION_OWNER",
    "DPM_OWNER",
    "SYSTEM",
]
AdvisorCockpitSlaAgeBand = Literal[
    "NOT_DUE",
    "DUE_SOON",
    "DUE_NOW",
    "OVERDUE",
    "CRITICAL_OVERDUE",
    "NOT_APPLICABLE",
]
AdvisorCockpitActionFamily = Literal[
    "CLIENT_MEETING_PREPARATION",
    "PROPOSAL_READY_FOR_REVIEW",
    "PROPOSAL_BLOCKED_BY_SOURCE_GAP",
    "POLICY_REVIEW_REQUIRED",
    "APPROVAL_DEPENDENCY_AGING",
    "CLIENT_CONSENT_REQUIRED",
    "MEMO_PACKAGE_BLOCKED",
    "REPORT_RENDER_ARCHIVE_BLOCKED",
    "EXECUTION_HANDOFF_READY",
    "EXECUTION_STATUS_ATTENTION",
    "HOUSE_VIEW_IMPACT_REVIEW",
    "WORKSPACE_DRAFT_STALE",
    "CLIENT_FOLLOW_UP_REQUIRED",
    "SUPPORTABILITY_DEGRADED",
    "UNSUPPORTED_CAPABILITY",
]
CockpitEvidenceAccessClass = Literal[
    "CUSTOMER_CONSUMABLE_SUMMARY",
    "RESTRICTED_CUSTOMER_EVIDENCE",
    "OPERATOR_ONLY_SUPPORTABILITY",
    "INTERNAL_ONLY_DIAGNOSTICS",
]
CockpitDependencyState = Literal["READY", "DEGRADED", "UNAVAILABLE", "NOT_CONFIGURED"]
AdvisorCockpitUnsupportedCapability = Literal[
    "CLIENT_READY_PUBLICATION",
    "EXTERNAL_CLIENT_COMMUNICATION",
    "CRM_SYSTEM_OF_RECORD",
    "CALENDAR_SCHEDULING",
    "OMS_ORDER_LIFECYCLE",
    "COMPLETED_POLICY_APPROVAL_AUTHORITY",
    "COMPLETED_POLICY_SIGN_OFF_AUTHORITY",
    "FULL_RFC0028_DEMO_RFP_PACKAGE",
]
